### ISSUE TITLE
Async Updating

### ISSUE THREAD

**Issue by sydneybrokeit** [hschreck/Panucci#13]
Rather than refreshing the page each time (which I think is stressing the lower-end machines), I'd like to implement asynchronous updating using jQuery.

@128keaton, what are your thoughts on this, outside of "ick, jQuery"?

**Comment by 128keaton** [comment]
we could probably do this easily.

**Comment by sydneybrokeit** [comment]
I figured as much.  I'll try to get it on my own before you get in.

**Comment by sydneybrokeit** [comment]
I started on it, latest 2 commits!

**Comment by 128keaton** [comment]
👏🏿👏🏿👏🏿👏🏿

**Comment by 128keaton** [comment]
(👏🏿👏🏿👏🏿👏🏿  )^2
